#
# Copyright (C) 2014 SANYO Techno Solutions Tottori Co., Ltd.
#

obj-y := \
	pxa1928_ma01.o \
	../common/ddr_tests.o

obj-$(CONFIG_POWER_LC709203F) += fg_lc709203f.o
obj-$(CONFIG_POWER_BQ24160) += chrg_bq24160.o
obj-$(CONFIG_POWER_MA01) += bat_ma01.o

obj-$(CONFIG_VIDEO_VX5B1D) += vx5b1d.o
